/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.io.IOException;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, IOException {
        //TestCases tests = new TestCases(); // Initialize your test class
        //SearchAmazon search = new SearchAmazon();
        //Linkedin watchAll = new Linkedin();
        //PicPostLink watchPost = new PicPostLink();
        //HyperLinksCount count = new HyperLinksCount();
        //ImageUrl count = new ImageUrl();
        //NestedFramesAutomation frameMove = new NestedFramesAutomation();
        //ImdbRatings ratings = new ImdbRatings();
        Windows_Handle windows = new Windows_Handle();

        //TODO: call your test case functions one after other here
        //tests.testCase01();
        //search.search_Amazon();
        //watchAll.linke_Din();
        //watchPost.pic_postLink();
        //count.Hyper_Links();
        //count.Img_Url();
        //frameMove.Nested_Frames();
        //ratings.Imdb_Ratings();
        windows.windows_Handle();
        
        //END Tests //tests.endTest(); // End your test by clearning connections and closing browser
        //search.endTest();
        //watchAll.endTest();
         //watchPost.endTest();
         //count.endTest();
         //count.endTest();
         //frameMove.endTest();
         //ratings.endTest();
         windows.endTest();
        
    }

    public static void main(String[] args) throws InterruptedException, IOException {
        new App().getGreeting();
    }
}
